### DISCUSSION TITLE
Adjusting Title in Title Card's Font Size?

### DISCUSSION THREAD

**Discussion by iamronr** [MelleD/lovelace-expander-card#379] [Q&A] [answered]
Is there a way to adjust the title size in the title card? Right now it's showing a little bigger than I'd like, and would like to bring it more in line with the rest of my dashboard...

```
title-card:
  square: false
  type: grid
  cards:
    - type: tile
      entity: sensor.radarr_movies
      name: Movies
    - type: tile
      entity: sensor.radarr_queue
      name: Queue
  columns: 2
  title: Radarr
  card_mod:
    style: |
      ha-card {
        --card-primary-font-size: 2rem;
        --card-secondary-font-size: 20px;
      }
```

**Comment by MelleD** [comment, marked as answer]
You are using no title card. If you use a title card like mushroom title card you can do what every you want.

**Reply by iamronr** [reply]
Got it. So if I'm using the embedded title in expander-card, I won't be able to adjust font size?

**Reply by iamronr** [reply]
Here's another example:

How would I adjust the font size for the title here:

```
type: custom:expander-card
title-card-button-overlay: false
clear: true
padding: 0em
title-card:
  type: custom:mushroom-title-card
  title: Usenet Links
cards:
  - type: entities
    entities:
      - type: weblink
        url: https://drunkenslug.com/
        name: DrunkenSlug
        icon: mdi:link
      - type: weblink
        url: https://ninjacentral.co.za/
        name: NinjaCentral
        icon: mdi:link
      - type: weblink
        url: https://althub.co.za/
        name: AltHub
        icon: mdi:link
      - type: weblink
        url: https://nzbgeek.info/
        name: NZBGeek
        icon: mdi:link
      - type: weblink
        url: https://animetosho.org/
        name: AnimeTosho
        icon: mdi:link
    title: Indexers
    theme: Mushroom
  - type: entities
    entities:
      - type: weblink
        url: https://whatsmyuse.net/
        name: What's My Usenet
        icon: mdi:link
      - type: weblink
        url: https://newshosting.com/
        name: NewsHostings
        icon: mdi:link
      - type: weblink
        url: https://newsgroupdirect.com/
        name: NewsGroupDirect
        icon: mdi:link
    title: Providers
    theme: Mushroom
```
![TRC](https://github.com/user-attachments/assets/7b26eea8-fb7e-448b-b9e8-36246b6d54d2)
