### ISSUE TITLE
Touchlistener with custom:digital-clock is not working

### ISSUE THREAD

**Issue by MelleD** [MelleD/lovelace-expander-card#204]
When using a custom:digital-clock as title card the touch listener to open and close is not working. The click listener is working

Example
```
          - type: custom:expander-card
            child-margin-top: 0.6em
            padding: 0
            clear: true
            title-card-button-overlay: true
            title-card-clickable: true
            expanded: false
            title-card:
              type: "custom:digital-clock"
              dateFormat:
                weekday: "long"
                day: "2-digit"
                month: "short"
              timeFormat:
                hour: "2-digit"
                minute: "2-digit"
```
