### ISSUE TITLE
Possible to template "expanded" state?

### ISSUE THREAD

**Issue by jabronimus** [MelleD/lovelace-expander-card#212]
This is a great card, so thank you for making this!

The feature I would like is the ability to "template" the "expanded" state.  As an example, instead of ```expanded: true``` or ```expanded: false```, I would like to be able to do something like the following:

```
expanded: |
  {% if states('input_boolean.washing_machine_running') == 'on' %}
    true
  {% else %}
    false
  {% endif %}
  ```

**Comment by MelleD** [comment]
This is exactly what is currently not possible and for this you would have to control the HA backend. A good place to start could be the mushroom card. That's where it was implemented.

If anyone has experience with this, I would be happy if someone could contribute this feature.

Maybe it is also possible to set the status via card mod. Haven't tried it myself yet.

**Comment by jabronimus** [comment]
Yeah, I mean I could use a conditional card, duplicate the expander card info with one version being "expanded: true" and one version being "expanded: false", and set the conditions in the conditional card ... but that's like ... a LOT of work.

A decluttering template might also be an option.

**Comment by MelleD** [comment]
> but that's like ... a LOT of work.

It depends, i'am using the YAML Mode in HA for my UI. There you can move the the complete expander card into one file and then just reuse it in your conditional card with !include.
I do this a lot to have only one single place when I have cards in more than one places in my UI.

e.g.

```
      - type: conditional
        condtions:
          - condition: state
            entity: sensor.waschmaschine
            state: "on"
        card: 
          - type: custom:expander-card
            expanded: true
            cards: !include my-expander.yaml
      - type: conditional
        condtions:
          - condition: state
            entity: sensor.waschmaschine
            state: "off"
        card: 
          - type: custom:expander-card
            expanded: false
            cards: !include my-expander.yaml
```

**Comment by jabronimus** [comment]
That's what i ended up doing, so i'm going to consider this closed

**Comment by MelleD** [comment]
From my point of view it can remain open, the feature definitely makes sense to offer template support :)

**Comment by rodehoed** [comment]
Hi all. And especially @MelleD , the include trick. Can this be used to change the background color of the expand card too based on a sensors state too? 

And btw great work! I think it should be include in HA by default, such a handy and space saving function!

**Comment by MelleD** [comment]
Yes why not you can create 2 cards with different background and check with conditional which you would like to show.
Or you try card mod https://github.com/MelleD/lovelace-expander-card?tab=readme-ov-file#card-mod

**Comment by mdagbro** [comment]
Hi! I was looking for this feature too to automatically expand the room I'm in. 

I understand having a template may be impossible for now.. But how about tying it to a binary_sensor? Would that be possible? Then we could create helper sensors with templates (or use existing sensors)

**Comment by dcapslock** [comment]
Now 2.5.0 uses conditional-card as wrapper, there will be possibility of subcribing to a template then use the template result as conditional rule to hide/show card(s). For this to be implmented, conditional card will need to get the Boolean rule as [proposed](https://github.com/home-assistant/architecture/discussions/1257), so then template results can be easily passed through to the conditional card Boolean rule config.

**Comment by dcapslock** [comment]
Revisting this and if suits I propose Javascript templates like button-card. I am working with the developer of [home-assistant-javascript-templates](https://github.com/elchininet/home-assistant-javascript-templates) to fine tune a few parts of the ibrary and then will work on a PR for expander-card. Ultimately the solution should allow for templating more than just exapnder-state, though that will be the first test case as it is also the more complex given other config which affects default expander state.

**Comment by MelleD** [comment]
For me that’s fine. In my dashboard expander card and button cards are the main items. I really like the button cards and use the JS framework.

**Comment by dcapslock** [comment]
WIP with PR #821 

```yaml
type: custom:expander-card
title: Expander Card
cards:
  - show_name: true
    show_icon: true
    type: button
    entity: light.test_group
expanded: |
  [[[
    return variables.input_boolean;
  ]]]
variables:
  input_boolean: |
    [[[
      return is_state('input_boolean.test_boolean', 'on');
    ]]]
```

or simpler without variable

```yaml
type: custom:expander-card
title: Expander Card
cards:
  - show_name: true
    show_icon: true
    type: button
    entity: light.test_group
expanded: |
  [[[
    return is_state('input_boolean.test_boolean', 'on');
  ]]]
```

https://github.com/user-attachments/assets/45b53d3a-586c-42c6-84ef-8c532ff056a9

**Comment by MelleD** [comment]
That's really cool :).

**Comment by dcapslock** [comment]
Due to ease of integrating UI editor, schema updated. Follows general style schema for frontend when using lists.

```yaml
type: custom:expander-card
title: Expander Card
cards:
  - show_name: true
    show_icon: true
    type: button
    entity: light.test_group
variables:
  - variable: test
    value_template: |
      [[[
        return is_state('input_boolean.test_boolean', 'on');
      ]]]
templates:
  - template: expanded
    value_template: |
      [[[
        return variables.test;
      ]]]
```
