### ISSUE TITLE
Not working in Home Assistant mobile app (Android)

### ISSUE THREAD

**Issue by arittner** [MelleD/lovelace-expander-card#216]
I switched from https://github.com/Alia5/lovelace-expander-card to this fork, but the issue exists in both projects. I can expand the cards in my browser (Firefox, Windows), but with the Home Assistant mobile app (on Android, well known as Companion App) expanding is not working. Only the icon flips around.

I have cards with closed state as default, so it's not possible to open the card and see the content.

Core: 2024.7.3
Supervisor: 2024.06.2
Operating System: 12.4
Frontend: 20240710.0

Companion-App: 2024.6.1-full

**Comment by arittner** [comment]
A small screencast about this issue: 

https://github.com/user-attachments/assets/ee65ea40-2d61-4a31-81ba-4497d49107ae

**Comment by MelleD** [comment]
Can you send your code as yaml and as [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)? Looks more your inner cards are broken.

But if the issue is only on the App, then you have to open a bug on the Companion App
See: https://github.com/home-assistant/android

On my Android tablet I see no issue currently

**Comment by mehne** [comment]
I can second this issue. I have it too.

**Comment by MelleD** [comment]
Not sure what I can say more than my comment

**Comment by arittner** [comment]
Hi!

Apologies for my delayed response.

```yaml
type: custom:expander-card
gap: 0.6em
padding: 1em
clear: false
title: WLAN Gastzugang QR Code
overlay-margin: 2em
child-padding: 0.5em
button-background: transparent
cards:
  - show_state: false
    show_name: false
    camera_view: auto
    type: picture-entity
    entity: image.fritz_box_7530_ax_z9_nazissinddoof_gastzugang
    image: https://demo.home-assistant.io/stub_config/bedroom.png
    name: WLAN Gastzugang
layout_options:
  grid_columns: 2
  grid_rows: 1
child-margin-top: 0.5em
```

Btw., I use the new "sections-view" for my dashboards.

Best regards, Josh.

**Comment by MelleD** [comment]
a) What is ?
```
layout_options:
  grid_columns: 2
  grid_rows: 1
```
b) With your code everything is working:
See: Tested with a fake image and real image on Android. Everything is fine

![bild](https://github.com/user-attachments/assets/18dfc0b8-98f4-4a80-9055-4acc8cf6588c)
![bild2](https://github.com/user-attachments/assets/c3ddd710-69de-4d46-9577-0caffb669937)
![bild3](https://github.com/user-attachments/assets/fb495f27-840d-4f53-a8f9-6b5a9739f04b)
![bild4](https://github.com/user-attachments/assets/bd72dce4-d74c-45c3-9ea0-40c21f80db9f)



c) See section what is a MRE. Maybe start with a empty dashboard and go step by step till the issue occurs and post the whole dashboard

d) See in companion app how to check if this really a app issue, then open there a bug

e) how do the card looks like without expander?

**Comment by arittner** [comment]
Hi!

for a)

> Btw., I use the new "sections-view" for my dashboards.

See https://www.home-assistant.io/dashboards/sections/

for c)

I can try it with another dashboard layout, but I started from scratch and it's not working. It could be possible, that the expander is not working with the new section layout on mobile.

for d)

I can try to open a bug in companion app about a 3rd party extension, but I'm not sure.

best regards, Josh.

**Comment by MelleD** [comment]
I see not what I can fix here, also looks:
> The sections view was released beginning of March 2024 and is experimental! Do not build your daily dashboard on top of it yet! We are still collecting feedback.
It is not possible to migrate dashboards into sections view.

If it only happens on the Android App, it looks more than a issue on the App side. Also if it is experimental feature


I also have a section dashboard.
Complete yaml
```
type: sections
path: test-sektion
max_columns: 2
title: test sektion
sections:
  - type: grid
    cards:
      - type: custom:expander-card
        gap: 0.6em
        padding: 1em
        clear: false
        title: WLAN Gastzugang QR Code
        overlay-margin: 2em
        child-padding: 0.5em
        button-background: transparent
        cards:
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: image.staubi_karte
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            name: WLAN Gastzugang
        layout_options: null
        child-margin-top: 0.5em
  - type: grid
    cards:
      - type: custom:expander-card
        gap: 0.6em
        padding: 1em
        clear: false
        title: WLAN Gastzugang QR Code
        overlay-margin: 2em
        child-padding: 0.5em
        button-background: transparent
        cards:
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: image.staubi_karte
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            name: WLAN Gastzugang
        layout_options: null
        child-margin-top: 0.5em
  - type: grid
    cards:
      - type: custom:expander-card
        gap: 0.6em
        padding: 1em
        clear: false
        title: WLAN Gastzugang QR Code
        overlay-margin: 2em
        child-padding: 0.5em
        button-background: transparent
        cards:
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: image.staubi_karte
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            name: WLAN Gastzugang
        layout_options: null
        child-margin-top: 0.5em
  - type: grid
    cards: []
  - type: grid
    cards:
      - type: custom:expander-card
        gap: 0.6em
        padding: 1em
        clear: false
        title: WLAN Gastzugang QR Code
        overlay-margin: 2em
        child-padding: 0.5em
        button-background: transparent
        cards:
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: image.fritz_box_7530_ax_z9_nazissinddoof_gastzugang
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            name: WLAN Gastzugang
        layout_options: null
        child-margin-top: 0.5em
  - type: grid
    cards:
      - type: custom:expander-card
        gap: 0.6em
        padding: 1em
        clear: false
        title: WLAN Gastzugang QR Code
        overlay-margin: 2em
        child-padding: 0.5em
        button-background: transparent
        cards:
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: image.fritz_box_7530_ax_z9_nazissinddoof_gastzugang
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            name: WLAN Gastzugang
        layout_options: null
        child-margin-top: 0.5em
```
![Bildschirmfoto 2024-08-26 um 16 08 36](https://github.com/user-attachments/assets/47d37abd-3688-44a5-8c8b-3f8add980b31)

So how I said maybe a complete MRE makes more sense then just a partial yaml
