### ISSUE TITLE
(Some!) Cards not expending first time clicking 

### ISSUE THREAD

**Issue by woempiej** [MelleD/lovelace-expander-card#269]
Hi,

Since updated to version 2.2.0 I'm encountering problems with expanding some cards when clicking on them at the first time when opening HA dashboard.

Environments:
HA Android app
Firefox with cleared cache and history (all time) 

![afbeelding](https://github.com/user-attachments/assets/91a5bca4-f173-4056-aff7-cd8ecc706d13)

Below a video;

https://github.com/user-attachments/assets/3dfb4a06-f894-47eb-afca-74683f984b97

In the video I first click on "Rolgordijnen" then "Muziek" and the "Het Weer"
If I would click on one of the above mentioned cards again it will expand correctly.
The other cards are working fine.

Below the config of the "Rolgordijnen" card

```
type: custom:expander-card
gap: 0.0em
expanded-gap: 0.6em
padding: 0.0em
clear: true
title: 🪟 ROLGORDIJNEN
overlay-margin: 0.0em
child-padding: 0.0em
child-margin-top: 0.0em
button-background: transparent
expander-card-background: var(--ha-card-background,var(--card-background-color,#fff))
header-color: var(--primary-text-color,#fff)
arrow-color: var(--arrow-color,var(--primary-text-color,#fff))
expander-card-display: block
title-card-clickable: false
min-width-expanded: 0
max-width-expanded: 0
cards:
  - type: custom:mushroom-template-card
    primary: ''
    secondary: VOORKANT
    icon: ''
    layout: vertical
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
    card_mod:
      style: |
        ha-card {
          background: none;
          box-shadow: none;
          border: none;
        }`;
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: automation.trigger
              data:
                skip_condition: false
              target:
                entity_id: automation.rolgordijnen_woonkamer_voorkant_open
            card_mod:
              style: |
                ha-card {
                  background-color: rgba(260, 260, 260, .1);
                }`;
            name: OPEN
            theme: material_dark_red
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: automation.trigger
              data:
                skip_condition: false
              target:
                entity_id: automation.rolgordijnen_woonkamer_voorkant_open_50
            name: Open 50%
            card_mod:
              style: |
                ha-card {
                  background-color: rgba(70, 70, 70, .1);
                }`;
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: automation.trigger
              data:
                skip_condition: false
              target:
                entity_id: automation.rolgordijnen_woonkamer_voorkant_open_100
            name: Open 100%
            card_mod:
              style: |
                ha-card {
                  background-color: rgba(70, 70, 70, .1);
                }`;
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: automation.trigger
              data:
                skip_condition: false
              target:
                entity_id: automation.rolgordijnen_woonkamer_voorkant_dicht
            name: DICHT
            theme: material_dark_red
            card_mod:
              style: |
                ha-card {
                  background-color: rgba(260, 260, 260, .1);
                }`;
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: input_boolean.turn_on
              target:
                entity_id: input_boolean.echo_block_the_sun
              data: {}
            name: Schaduw
            card_mod:
              style: |
                ha-card {
                  background-color: rgba(70, 70, 70, .1);
                }`;
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: cover.stop_cover
              data: {}
              target:
                entity_id:
                  - cover.lumi_lumi_curtain_acn002_cover
                  - cover.lumi_lumi_curtain_acn002_cover_2
            name: STOP
            card_mod:
              style: |
                ha-card {
                  color: red;
                  background-color: rgba(180, 35, 35, .1);
                }
  - type: custom:mushroom-template-card
    primary: ''
    secondary: ZIJ EN ACHTERKANT
    icon: ''
    layout: vertical
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
    card_mod:
      style: |
        ha-card {
          background: none;
          box-shadow: none;
          border: none;
        }`;
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: automation.trigger
              data:
                skip_condition: false
              target:
                entity_id: automation.rolgordijnen_woonkamer_zij_en_achterkant_open
            name: OPEN
            theme: material_dark_red
            card_mod:
              style: |
                ha-card {
                  background-color: rgba(260, 260, 260, .1);
                }`;
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: automation.trigger
              data:
                skip_condition: false
              target:
                entity_id: automation.rolgordijnen_woonkamer_zij_en_achterkant_open_50
            name: Open 50%
            card_mod:
              style: |
                ha-card {
                  background-color: rgba(70, 70, 70, .1);
                }`;
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: automation.trigger
              data:
                skip_condition: false
              target:
                entity_id: automation.rolgordijnen_woonkamer_zij_en_achterkant_open_100
            name: Open 100%
            card_mod:
              style: |
                ha-card {
                  background-color: rgba(70, 70, 70, .1);
                }`;
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: automation.trigger
              data:
                skip_condition: false
              target:
                entity_id: automation.rolgordijnen_woonkamer_zij_en_achterkant_dicht
            name: DICHT
            theme: material_dark_red
            card_mod:
              style: |
                ha-card {
                  background-color: rgba(260, 260, 260, .1);
                }`;
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: automation.trigger
              data:
                skip_condition: false
              target:
                entity_id: automation.rolgordijn_woonkamer_achterkant_tuinzicht
            name: Tuinzicht
            card_mod:
              style: |
                ha-card {
                  background-color: rgba(70, 70, 70, .1);
                }`;
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: call-service
              service: cover.stop_cover
              data: {}
              target:
                entity_id:
                  - cover.lumi_lumi_curtain_acn002_cover_3
                  - cover.lumi_lumi_curtain_acn002_cover_4
                  - cover.lumi_lumi_curtain_acn002_cover_5
            icon: ''
            name: STOP
            card_mod:
              style: |
                ha-card {
                  color: red;
                  background-color: rgba(180, 35, 35, .1);
                }
```

If more information is needed let me know.
Logfiles of HA are clear.

**Comment by woempiej** [comment]
The "Energie" card is having the same problem (less code)

```
type: custom:expander-card
gap: 0.0em
expanded-gap: 0.6em
padding: 0.0em
clear: true
title: ⚡ ENERGIE
overlay-margin: 0.0em
child-padding: 0.0em
child-margin-top: 0.0em
button-background: transparent
expander-card-background: var(--ha-card-background,var(--card-background-color,#fff))
header-color: var(--primary-text-color,#fff)
arrow-color: var(--arrow-color,var(--primary-text-color,#fff))
expander-card-display: block
title-card-clickable: false
min-width-expanded: 0
max-width-expanded: 0
cards:
  - type: custom:mushroom-template-card
    primary: ''
    secondary: REALTIME STROOM
    icon: ''
    layout: vertical
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: custom:power-flow-card
    entities:
      grid: sensor.p1_meter_3c39e72f4cec_active_power
      solar: sensor.pv_power
    watt_threshold: 1000
    kw_decimals: 1
  - type: entities
    entities:
      - entity: sensor.pv1_power
        name: Vermogen String 1
        icon: mdi:solar-power-variant
      - entity: sensor.pv2_power
        name: Vermogen String 2
        icon: mdi:solar-power-variant
  - type: custom:mushroom-template-card
    primary: ''
    secondary: Stroomverbruik vandaag
    icon: ''
    layout: vertical
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: energy-usage-graph
  - type: custom:mushroom-template-card
    primary: ''
    secondary: Gasverbruik vandaag
    icon: ''
    layout: vertical
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: energy-gas-graph
  - type: custom:mushroom-template-card
    primary: ''
    secondary: Waterverbruik vandaag
    icon: ''
    layout: vertical
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: energy-water-graph
  - type: custom:mushroom-template-card
    primary: ''
    secondary: TOTAAL VERBRUIK VANDAAG
    icon: ''
    layout: vertical
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: energy-distribution
  - type: energy-devices-graph
```
