### ISSUE TITLE
Cards always expanded and unable to collapse since 2.2.1

### ISSUE THREAD

**Issue by Caligo82** [MelleD/lovelace-expander-card#316]
Ever since the update to Version 2.2.1 and the following [fix](https://github.com/MelleD/lovelace-expander-card/pull/272) I have the problem that I am unable to close nested (conditional) expander cards. They just stay open all the time. It works fine with 2.2.0. It unfortunatly happens with every browser I tested.

this is my code:

```
type: custom:expander-card
gap: 10em
padding: em
child-padding: em
clear: true
title: Expander
overlay-margin: 2em
title-card-button-overlay: true
button-background: transparent
title-card:
  type: picture
  image: /local/chalettimer.jpg
  tap_action: none
expanded: false
cards:
  - type: vertical-stack
    cards:
      - type: custom:mushroom-template-card
        primary: Putzen checkout
        expanded: false
        gap: em
        padding: em
        child-padding: em
        clear: true
        title: Expander
        overlay-margin: 0.5em
        title-card-button-overlay: true
        title-card-clickable: true
        button-background: transparent
        child-margin-top: 0.5em
        title-card:
          type: custom:mushroom-template-card
          primary: Putzen checkout
          expanded: false
title-card-padding: ""
child-margin-top: 0.5em
title-card-clickable: true
expander-card-display: ""
```
