### ISSUE TITLE
Laggy expand animation

### ISSUE THREAD

**Issue by henningWoehr** [MelleD/lovelace-expander-card#335]
Hi, I just started using your expander card (2.2.6). It works just fine, but I immediatly noticed that the expanding animation is a bit laggy.
![expander-card-animation](https://github.com/user-attachments/assets/47657cc3-73d1-495d-9b83-a8ae6f0d6fa3)
I hope it is visible in the gif, but simply put, the expander expands just a bit (maybe ~100px?) and then instantly expands to the rest of the height.

The example I used:
```yaml
type: custom:expander-card
child-margin-top: 0.6em
padding: 0
clear: true
title-card-button-overlay: true
title-card-clickable: true
expanded: false
title-card:
  type: heading
  icon: ""
  heading: Test
  heading_style: title
cards:
  - type: vertical-stack
    cards:
      - type: picture
        image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png

```
