### ISSUE TITLE
Expander card not rendering iframe properly

### ISSUE THREAD

**Issue by Caligo82** [MelleD/lovelace-expander-card#351]
Since version 2.3.0 I have problems with an iframe embedded within an expander card. It sets the zoom level to maximum, makes the roundshot non scrollable and puts every icon on the top left corner.

standard iframe (working)
```
type: iframe
url: https://matterhorngotthardbahn.roundshot.com/oberwald/#/
aspect_ratio: "1"
```
looks like this:
![image](https://github.com/user-attachments/assets/c008b54d-6322-492b-89f7-5960f55e9d0f)

embedded iframe (not working)
```
type: custom:expander-card
cards:
  - type: iframe
    url: https://matterhorngotthardbahn.roundshot.com/oberwald/#/
    aspect_ratio: "1"
```
looks like this:
![image](https://github.com/user-attachments/assets/467261dc-a19f-4eaf-9497-90baf998a03c)
