### ISSUE TITLE
Expand Upward / Replace caret with templatized text

### ISSUE THREAD

**Issue by HeedfulCrayon** [MelleD/lovelace-expander-card#360]
**Is your feature request related to a problem? Please describe.**
I currently have a solution for this that I forked and modified myself.  I am no front-end dev, so it is probably done horribly.
I would like to be able to have the card expand upward, and replace the caret with templatized text as additional options.  
Here is an example in action:
![collapsible-card](https://github.com/user-attachments/assets/0d0b07c5-ec81-4dbb-8ba6-4022ed6a378f)

**Describe the solution you'd like**
It would be cool for this feature to actually be implemented in a card that is being updated regularly

**Describe alternatives you've considered**
Keep using my implementation until it breaks

**Additional context**
My implementation can be found here [https://github.com/HeedfulCrayon/lovelace-collapsable-card](https://github.com/HeedfulCrayon/lovelace-collapsable-card)

**Comment by dcapslock** [comment]
Since version 4.3.0, which inctroduced title template, this is now fully possible.

```yaml
type: custom:expander-card
title: Expander Card
icon: mdi:chevron-up
expander-card-id: my_expander_id
expander-card-display: flex
cards:
  - type: tile
    name: Sun Tile 1
    entity: sun.sun
    vertical: false
    features_position: bottom
  - type: tile
    name: Sun Tile 2
    entity: sun.sun
    vertical: false
    features_position: bottom
  - type: tile
    name: Sun Tile 3
    entity: sun.sun
    vertical: false
    features_position: bottom
style: |
  /* Set flex direction for children-container now display is flex */
  .children-container {
    flex-direction: column;
  }
  /* Have children contaner first by setting expander-card to be flex-direction: column-reverse */
  .expander-card {
    flex-direction: column-reverse;
  }
  /* Align title center */
  .title {
    text-align: center !important;
  }
  /* Hide the icon */
  .ico {
    display: none;
  }
templates:
  - template: title
    value_template: |-
      [[[
        return variables.my_expander_id_open ? 'OPEN' : 'CLOSED';
      ]]]
```

https://github.com/user-attachments/assets/d8fb12ba-8714-4125-a23e-e47fa86f4e97
