### ISSUE TITLE
Change position of Expander Button from right to left

### ISSUE THREAD

**Issue by Kilowatt-W** [MelleD/lovelace-expander-card#426]
Good Morning and thx for this cool lovelace thing :-)

A the moment it is not possible to switch the location of the expander button from right to left.

I would appreciate a setting like

'expander_position: [left,right]'

to switch it.

My problem is with a cover tile in the expander title. There is the down button from the cover-group and next to it the expander, so it looks a bit crazs :-)

Maybe this could be an nice Feature in the future,

greetings from Austria

Kilowatt

**Comment by dcapslock** [comment]
You can do with card_mod.

```yaml
card_mod:
  style: |
    .header {
      flex-direction: row-reverse !important;
    }
```
