### ISSUE TITLE
Overlay underneath the title card.

### ISSUE THREAD

**Issue by Bawt818** [MelleD/lovelace-expander-card#470]
When a [Big Slider Card](https://github.com/nicufarmache/lovelace-big-slider-card) is used as a title card the overlay is drawn underneath it. 

![Image](https://github.com/user-attachments/assets/e2fecec2-cb4b-4f98-b3a7-7926d46c91e0)

The issue exists on gecko, chromium and in the android companion app.
Card mod can be used as a temporary fix:
```
type: custom:expander-card
child-margin-top: 0.6em
padding: 0em
clear: true
title-card-button-overlay: true
overlay-margin: 0.55em
card_mod:
  style: |
    .header-overlay {
      z-index: 1;
    }
title-card:
  type: custom:big-slider-card
  entity: light.living_room_lights
```

![Image](https://github.com/user-attachments/assets/9e13d541-8b41-46dc-87d3-e6ca85307631)

Still, it'd be great if a fix could be implemented directly.

Thanks!

**Comment by MelleD** [comment]
I cannot reproduce it and you send different examples. You can try all padding, margin and gap options from here:
https://github.com/MelleD/lovelace-expander-card e.g. `title-card-padding`

Your card mod make completely different things in my case and is not working.

But if you find a solution with card mod everything is fine. 

Without padding, above my card below your card mod title and all is not working:

<img width="559" alt="Image" src="https://github.com/user-attachments/assets/cfce882d-753a-4ad7-895d-eebeb81253a8" />


With padding, above my card below your card mod title and all is not working:

<img width="539" alt="Image" src="https://github.com/user-attachments/assets/6589bc14-2158-45f6-87e8-15f873cfc6a5" />

So for me everything looks fine and worked as expected.


```
      - type: custom:expander-card
        button-background: red
        padding: 0em
        expander-card-background: red
        title-card:
          type: custom:big-slider-card
          entity: light.theater_volume
        cards:
          - type: "custom:digital-clock"
            dateFormat:
              weekday: "long"
              day: "2-digit"
              month: "short"
            timeFormat:
              hour: "2-digit"
              minute: "2-digit"
```
