### ISSUE TITLE
On iOS title-card-clickable: false needs two taps to expand

### ISSUE THREAD

**Issue by hacki11** [MelleD/lovelace-expander-card#482]
**Is your feature request related to a problem? Please describe.**
I have a `tile` card as `title_card` which has a `icon_tap_action` to toggle the power of the entity behind (aircon).
`tap_action` is set to `none` and `title-card-clickable` is `true`.
I want to be able to click on the icon to toggle power and click on the title card to expand/collapse.
Unfortunately, clicking on the icon toggles _and_ expands with a single click. I would like to not expand/collapse if i click on the icon. Also moving the slider causes the box to expand.

**Describe the solution you'd like**
- Click on icon toggles the power of the entity behind the title-card tile
- Using other buttons/sliders in the title card do not expand the card
- Click on the rest of the title-card shall expand/collapse the `expander-card` 

**Describe alternatives you've considered**
Setting `title-card-clickable` to `false` and only use the expand/collapse button, but on iOS the expand/collapse button doesn't work if I toggled the power just before with the first tap. It requires two taps on this button to make it work. 

**Additional context**
Click on Icon:
![Image](https://github.com/user-attachments/assets/359bdb02-7b53-45b3-8e61-397dc112eab1)
Result:
![Image](https://github.com/user-attachments/assets/4c7cda0d-587a-4d20-a92c-c86daad75406)

Moving slider:
![Image](https://github.com/user-attachments/assets/687f3720-a1c4-4662-b3c3-1e64c4d3a755)
Result:
![Image](https://github.com/user-attachments/assets/51f859d7-6456-4b37-80d5-fccfcbe175b4)

```
type: custom:vertical-stack-in-card
cards:
  - type: custom:expander-card
    child-margin-top: 0.6em
    padding: 0
    clear: true
    title-card-button-overlay: false
    title-card-clickable: true
    expanded: false
    title-card:
      features:
        - type: custom:service-call
          entries:
            - type: slider
              entity_id: climate.e81656c0f418
              range:
                - 18
                - 26
              tap_action:
                action: perform-action
                target:
                  entity_id:
                    - climate.e81656c0f418
                perform_action: climate.set_temperature
                data: {}
              step: 0.5
              value_attribute: temperature
              haptics: false
              label: "{{ value }} {{ unit }}"
              icon: ""
              unit_of_measurement: °C
              thumb: default
      type: tile
      entity: climate.e81656c0f418
      features_position: inline
      vertical: false
      name: Klima
      icon: mdi:air-conditioner
      tap_action:
        action: none
      icon_tap_action:
        action: toggle
      card_mod:
        style: |
          ha-card {
            border: none;
          }
    hide_state: false
    state_content:
      - current_temperature
      - state
    cards:
      - type: tile
        entity: climate.e81656c0f418
        features_position: bottom
        name: Lüfter
        vertical: false
        hide_state: true
        tap_action:
          action: none
        icon: mdi:fan
        features:
          - type: custom:service-call
            entries:
              - type: selector
                entity_id: input_select.e81656c0f418_fanSpeed
                options:
                  - entity_id: input_select.e81656c0f418_fanSpeed
                    option: Auto
                    tap_action:
                      action: perform-action
                      perform_action: input_select.select_option
                      data:
                        option: Auto
                      target:
                        entity_id: input_select.e81656c0f418_fanSpeed
                    icon: mdi:fan-auto
                    label: Auto
                  - entity_id: input_select.e81656c0f418_fanSpeed
                    option: Min
                    tap_action:
                      action: perform-action
                      perform_action: input_select.select_option
                      data:
                        option: Min
                      target:
                        entity_id: input_select.e81656c0f418_fanSpeed
                    icon: mdi:fan-speed-1
                  - entity_id: input_select.e81656c0f418_fanSpeed
                    option: Medium
                    tap_action:
                      action: perform-action
                      perform_action: input_select.select_option
                      data:
                        option: Medium
                      target:
                        entity_id: input_select.e81656c0f418_fanSpeed
                    icon: mdi:fan-speed-2
                  - entity_id: input_select.e81656c0f418_fanSpeed
                    option: High
                    tap_action:
                      action: perform-action
                      perform_action: input_select.select_option
                      data:
                        option: High
                      target:
                        entity_id: input_select.e81656c0f418_fanSpeed
                    icon: mdi:fan-speed-3
                  - entity_id: input_select.e81656c0f418_fanSpeed
                    option: Turbo
                    tap_action:
                      action: perform-action
                      perform_action: input_select.select_option
                      data:
                        option: Turbo
                      target:
                        entity_id: input_select.e81656c0f418_fanSpeed
                    icon: mdi:car-turbocharger
                autofill_entity_id: true
                haptics: false
      - type: tile
        entity: climate.e81656c0f418
        name: Betriebsart
        tap_action:
          action: none
        icon: mdi:auto-mode
        state_content: state
        features:
          - type: climate-hvac-modes
```
