### ISSUE TITLE
Visibility condition not working in cards

### ISSUE THREAD

**Issue by 414ND1N** [MelleD/lovelace-expander-card#483]
when a card has a visibility condition it seems not to be applied correctly.

In the example you can see that depending on the first card value, the second card will be displayed, this works correctly in other places like a vertical stack, but inside the expander card it seems not to work correctly.

## Code:

```yaml
type: custom:expander-card
expanded: true
child-margin-top: 0.6em
cards:
  - type: custom:bubble-card
    card_type: select
    name: Always visible
    icon: mdi:check
    show_state: true
    entity: input_select.visible
  - type: custom:button-card
    name: Conditional visible
    icon: mdi:progress-question
    show_state: false
    show_icon: false
    visibility:
      - condition: state
        entity: input_select.visible
        state: Visible
```

## Images:

Red is expander card, blue is vertical stack *

![Image](https://github.com/user-attachments/assets/3777416a-51ce-42c0-ac52-fb9afa243342)

![Image](https://github.com/user-attachments/assets/268419d6-55b0-4493-911e-8cf107bd2916)

## Versions:

* expander card: 2.4.0
* home assistant Core: 2025.5.2 
* home assistant frontend: 20250516.0
* google chrome: 136.0.7103.114

**Comment by MelleD** [comment]
Hey @414ND1N,

please check you local browser. There is an error which shows you, that you are not using it correctly.

You cannot use the expander card as an layout. You need always a additional layout element.

In your case this should work

```
type: custom:expander-card
cards:
  - type: vertical-stack
    cards:
      - type: custom:bubble-card
        card_type: select
        name: Always visible
        icon: mdi:check
        show_state: true
        entity: input_select.visible
      - type: custom:button-card
        name: Conditional visible
        icon: mdi:progress-question
        show_state: false
        show_icon: false
        visibility:
          - condition: state
            entity: input_select.visible
            state: Visible
```
