### ISSUE TITLE
Swiper / Expander Bug?

### ISSUE THREAD

**Issue by FedgarLurch** [MelleD/lovelace-expander-card#484]
I am going to post this in both places and edit them to link to each other, because I truthfully don't know which thing is interfearing with which.

I have (Or the goal is) to have a swiper card that holds different lists inside of it, that is normally unexpanded. So it shows up narrow with just a list, and then from there when interacted with, expands and I can swipe between my various lists.

Problem is, the swipe function doesn't seem to work nested in there.

Here is the code:
```
type: custom:expander-card
cards:
  - type: custom:simple-swipe-card
    show_pagination: true
    card_spacing: 15
    swipe_direction: horizontal
    cards:
      - display_order: duedate_asc
        type: todo-list
        entity: todo.home_improvement
        title: Home Improvement
      - display_order: none
        type: todo-list
        entity: todo.wedding_list
        title: Wedding List

```

Now, the expanding part works fine, the thing that doesn't work is the swiping. See the below photos.

![Image](https://github.com/user-attachments/assets/b80719f3-5956-4ede-986e-79f6112a7dd0)

That is what happens when I try to swipe. There are no console errors and everything has been updated. 
I am happy to help debug, I just don't know where to start. 

Link to the other github side of things:
https://github.com/nutteloost/simple-swipe-card/issues/12

Thanks!

**Comment by MelleD** [comment]
Sorry I don’t get the issue. Could you please provide an MRE to reproduce it with standard components. 
Also you can try a layout (see other bugs) around your swipe card

**Comment by FedgarLurch** [comment]
I removed a few things, but its pretty much as cutdown as it can be. 
Todo lists are standard components aren't they? Its the same if I put button cards in there either way. 
As far as the other component, removing it removes the problem... but also is the whole point of what I am trying to do. I am trying to have a collapsed version of my lists, where upon expanding, lets me swipe between my lists and add things, mark things off, etc. 

That is why I linked these two issues, I am not sure which component is interfering with which, so I was hoping for some pointers on how to isolate / test things. If 

I tried what I think you were saying about the layout (wrapping things in a vertical stack for instance?

```
type: custom:expander-card
cards:
  - type: custom:simple-swipe-card
    show_pagination: true
    card_spacing: 15
    swipe_direction: horizontal
    cards:
      - type: vertical-stack
        cards:
          - display_order: duedate_asc
            type: todo-list
            entity: todo.home_improvement
            title: Home Improvement
      - type: vertical-stack
        cards:
          - display_order: none
            type: todo-list
            entity: todo.wedding_list
            title: Wedding List
```

And:

```
type: custom:expander-card
cards:
  - type: vertical-stack
    cards:
      - type: custom:simple-swipe-card
        show_pagination: true
        card_spacing: 15
        swipe_direction: horizontal
        cards:
          - display_order: duedate_asc
            type: todo-list
            entity: todo.home_improvement
            title: Home Improvement
          - display_order: none
            type: todo-list
            entity: todo.wedding_list
            title: Wedding List
```

Doesnt work either. Both of these cause the swipe function to become completely lost, rather than just not fully swiping.

**Comment by MelleD** [comment]
Here is a small example:

```
      - type: custom:expander-card
        cards:
          - type: vertical-stack
            cards:
              - type: custom:simple-swipe-card
                show_pagination: true
                card_spacing: 15
                swipe_direction: horizontal
                cards:
                  - display_order: duedate_asc
                    type: entity
                    entity: sun.sun
                  - display_order: none
                    type: entity
                    entity: sun.sun
```

but I think this issue here is well explained and see currently no solution to combine two container cards
https://github.com/nutteloost/simple-swipe-card/issues/12#issuecomment-2945748623
