### ISSUE TITLE
Unable to use horizontal stack in cards section on HA Core 2025.6

### ISSUE THREAD

**Issue by Maekoboss** [MelleD/lovelace-expander-card#506]
Hi after upgrading my HA Core from 2025.5.3 to 2.6.0 and later my expander card got broken. It looks like the issue is caused by using horizontal-stack as part of the cards content or title-card content.

expander-card version: 2.4.2

**This DOES NOT work. There is no issue message in console log, But the whole FE app just frezes and after some time it crashes:**
```
- type: custom:expander-card
  child-margin-top: 0.6em
  padding: 5px
  title: "Přízemí"
  title-card-button-overlay: true
  title-card-clickable: false
  overlay-margin: "5px"
  button-background: "#e6e6fa"
  expander-card-background: "#f8f8ff"
  cards:
    - type: horizontal-stack
      title: "Přízemí"
      cards:
        - name: "Off"
          type: button
          tap_action:
            action: perform-action
            perform_action: script.prizemi_heating_mode
            data:
              action_type: 'off'
    - type: heading
      heading: Ložnice 1
      icon: mdi:bed-double
```

**This set-up without the horizontal-stack works OK.**
```
- type: custom:expander-card
  child-margin-top: 0.6em
  padding: 5px
  title: "Přízemí"
  title-card-button-overlay: true
  title-card-clickable: false
  overlay-margin: "5px"
  button-background: "#e6e6fa"
  expander-card-background: "#f8f8ff"
  cards:
    - type: heading
      heading: Ložnice 1
      icon: mdi:bed-double
```

I am not sure if this is a specific issue to expander-card or more issue on HA side. But other cards works so therefore I am posting the issue here so you can investigate. THX

**Comment by nathbullen** [comment]
Having the exact same issue - took a while to pinpoint it but any dashboard pages with an expander card containing a horizontal stack cause the iOS app to immediately freeze when trying to open the page

**Comment by MelleD** [comment]
See here: https://community.home-assistant.io/t/expander-accordion-collapsible-card/738817/57

It depends on the layout of your view. If you are using sections then you have to rename `cards` to `sections`.

Also view type panel, sidebar and custom:grid-layout, sections,custom:masonry-layout etc. is working

Only Masonry not. I see nor error on the console, so I think you have to post this is issue for masonry type to the HA core team.

Additional a last information this is not related to the horizontal stack layout. Every nested grouping layout have this issue.

**Comment by MelleD** [comment]
Close this because of https://github.com/MelleD/lovelace-expander-card/issues/508 and https://github.com/MelleD/lovelace-expander-card/pull/509

If you have more infos please add it to the tickets or PR.
Thanks

**Comment by Maekoboss** [comment]
@MelleD it seems that the issue is resolved in HA Core version 2025.6.3.

With this version now this code (proposed solution) does not work:
```
views:
 - title: MyView
   path: my-view
   sections: ...
``` 

But the original code works OK:
```
views:
 - title: MyView
   path: my-view
   cards: ...
```
