### ISSUE TITLE
Masonry View is not working since HA Core 2025.6

### ISSUE THREAD

**Issue by MelleD** [MelleD/lovelace-expander-card#508]
Since HA Core 2025.6 nested layouts like horizontal-stack are not working with the expander card.
The browser is freezing and there are no error on the console logs. Could be a direct issue on the HA Core component.

Reproduce steps:

```
---
views:
  - title: Test
    path: test
    badges: []
    type: masonry
    cards:
      - type: custom:expander-card
        padding: 0
        child-margin-top: 0.6em
        title-card-clickable: true
        clear: true
        title-card-button-overlay: true
        title-card:
          type: entities
          entities:
            - entity: sun.sun
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
              - type: entities
                entities:
                  - entity: sun.sun

```

Links:
https://www.home-assistant.io/dashboards/masonry/
https://community.home-assistant.io/t/expander-accordion-collapsible-card/738817/56?u=melled

Possible workarounds:
Use another view type or use layout card custom:masonry-layout:
https://github.com/thomasloven/lovelace-layout-card

Presumably it could be a problem directly in HA-Core due to a change in the structure of the layout and subcards.
