### ISSUE TITLE
Overflow/Display error

### ISSUE THREAD

**Issue by hvorragend** [MelleD/lovelace-expander-card#88]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser
- [X] **And no other expand-fork loaded.** 

**Release with the issue:**

**Last working release (if known):**
Unknown

**Browser and Operating System:**
Safari/iOS

**Description of problem:**

There seem to be problems if the text in an entity card becomes too long. 

Firstly, the HA-Card and the childrencard grow with it. With `"display: block;"` instead of `"display: grid;"` it seems to work. 

Secondly, the font size is too large on a smartphone. But only if the friendly names are too long. Tested in Safari under iOS. 

**Additional information:**

no console errors
![IMG_2803](https://github.com/MelleD/lovelace-expander-card/assets/343705/e7bf5fdf-05aa-4194-afc5-0071dad11e14)
![IMG_2804](https://github.com/MelleD/lovelace-expander-card/assets/343705/af166703-c04c-4b7c-bd18-a8ec866aba95)
![IMG_2805](https://github.com/MelleD/lovelace-expander-card/assets/343705/1673f4dd-35a3-4cf2-a3fd-8d140624bd3a)

**Comment by hvorragend** [comment]
By the way: Why is the title link in color blue?

Until a few days ago I have used this fork https://github.com/clarinetJWD/lovelace-yet-another-expander-card and there is the link colored in primary color

**Comment by FoxxMD** [comment]
I'm also experiencing this issue. If it helps I am using the card in the **Sections** view type rather than the default Masonry but I see the issue occur on both types.

**Comment by MelleD** [comment]
Thanks for reporting. I didn’t changed the font size or the color so this should be reproducible also on the original one. 
Currently iam on vacation. So I can check it after (3 weeks) :-).
Currently my expander card title is white.

For your issue interesting I had the other way around with display blocks it didn’t work. I have to check if it really a issue with long friendly names

So closed looks like:
![IMG_2111](https://github.com/MelleD/lovelace-expander-card/assets/6340898/de0f83fa-6d5a-4e1c-91d9-817e0f6ee31f)


Open:
![IMG_2112](https://github.com/MelleD/lovelace-expander-card/assets/6340898/b7f6ccfe-013c-48a4-94d2-44c827bfce94)


Could your share your yaml code. Makes it easier to reproduce for me.

**Comment by FoxxMD** [comment]
You can reproduce by creating any card that renders a very long name for the entity. For instance:

![image](https://github.com/MelleD/lovelace-expander-card/assets/4663766/262f8854-6bf8-4fd9-b560-efa1e6b83d8c)

```yaml
type: custom:expander-card
gap: 0.6em
padding: 1em
clear: false
title: Expander
overlay-margin: 2em
child-padding: 0.5em
button-background: transparent
cards:
  - type: entities
    entities:
      - entity: sun.sun
        name: This is an entity with a very long name that breaks things
```

The same `entities` card outside of the expander

![image](https://github.com/MelleD/lovelace-expander-card/assets/4663766/053b04c5-53ee-4571-b80c-9f156a09b151)

I'm not using any custom themes or css

EDIT:

Removing the default CSS values _almost_ fixes things.

Removing `padding` `overlay-margin` and `child-padding` gets closer to normal:

![image](https://github.com/MelleD/lovelace-expander-card/assets/4663766/c07055eb-f8da-41ca-9218-900a47a289b4)

**Comment by MelleD** [comment]
Ok I will try it. I have good experience to start with 0 default values and then increase it, if needed.
Maybe we should change the default values with a major release.

The second issue with color. I saw I fixed it with card mod, because my PR was not merged in the original repo. I have to check my old PR and have to move it.

Third issue with font size, I have to look into deeper

**Comment by FoxxMD** [comment]
Overwriting the defaults or adding a note in the documentation about sane defaults sounds like a good idea. Though I think the overflow fix is more than just setting 0 over defaults since it doesn't _quite_ fix things and the actual fix should have the element respecting outside container width.

But these are all small issues that can wait till you get back from vacation! Enjoy.

**Comment by MelleD** [comment]
Yes the width issue I have to look into.
In the other issue (the person example), I tried to fix this issue here:
https://community.simon42.com/t/accordion-card/24772/30

You can look into the last PR there I added a css style for the layouting. 
Do you know if the original card have also this issue with long names? Or just try with 0.11 or 1.0.0 version.

**Comment by NeeeeB** [comment]
@MelleD I've just switched from the original card to yours, and I can confirm that the overflow bug with long names was already there in the original card.

**Comment by MelleD** [comment]
Hey @hvorragend 

> Firstly, the HA-Card and the childrencard grow with it. With "display: block;" instead of "display: grid;" it seems to work.

Where did you try it?
.expander-card did not work

<img width="408" alt="Bildschirmfoto 2024-05-25 um 12 37 17" src="https://github.com/MelleD/lovelace-expander-card/assets/6340898/160fb155-1e41-4d50-ac65-c62024835cab">


EDIT:

I guess the issue is the second label, when this is too long (see https://github.com/MelleD/lovelace-expander-card/issues/100). Additional problem is if you use padding.

AND on ios app it looks completely different and nothing is working :( 

See here with a smaller label it works:
<img width="383" alt="Bildschirmfoto 2024-05-25 um 13 28 43" src="https://github.com/MelleD/lovelace-expander-card/assets/6340898/6101a1d5-c3a5-46d4-aa1f-42eb720c668c">

I think i can fix the case when the second label is not too long with "block grid".

@FoxxMD maybe you can test your cases, if this fix will work for you.

Question: 
Who uses padding? I don't use it because it moves the whole heading

**Comment by MelleD** [comment]
@FoxxMD 

I tested again.

And there are several options.

You could set `display:block` as suggested from @hvorragend . However, you would have to rebuild the entire card, because the arrow would then no longer be on the right side. In addition, the padding on the card no longer works if you have a title card. That would almost be a complete rebuild. The effort is currently too much for me.

I looked at my own cards again and found out why I don't have a responsive layout problem: if you use a container as a child, then that works too.

Example 1 works:
```
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
```

Example 2 works:
```
      - type: custom:expander-card
        title: Expander
        cards:
          - type: custom:vertical-stack-in-card
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
```
Example 3 don't work with the default HA Layouts (off course):
```
      - type: custom:expander-card
        title: Expander
        cards:
          - type: vertical-stack
            cards:
              - type: entities
                entities:
                  - entity: sun.sun
                    name: This is an entity with a very long name that breaks things
```

I'm currently leaning towards including this in the documentation as best practice. This means that both ways are working, also the title card.
