### ISSUE TITLE
Top of expanded cards visible when collpased

### ISSUE THREAD

**Issue by FoxxMD** [MelleD/lovelace-expander-card#92]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

1.1.4

**Last working release (if known):**

**Browser and Operating System:**

Firefox 125.0.3 archlinux

The issue is reproducible on Chromium 124.0.6367.118

**Description of problem:**

The top of the expanded cards section is visible when the cards are collapsed. I just switched from alia5's version which worked correctly for me. This occurs for both title card and non-title card types and on both masonry and section view types. Visible on both mobile (android HA app) and desktop.

![image](https://github.com/MelleD/lovelace-expander-card/assets/4663766/e5209ed6-3162-4bf3-84eb-0df721c1295b)

**Javascript errors shown in the web inspector (if applicable):**

There are no relevant errors in the console.

```

```

**Additional information:**

Thanks for keeping this custom card updated! It's massively helpful even in the current state. <3

**Comment by MelleD** [comment]
Thanks for reporting.
Could you send me the yaml code how you use the card. Then I can create a test for that, because for my own cards it works.

**Comment by FoxxMD** [comment]
Removing the default value of `0.5em` for `child-padding` seems to fix the issue:

```yaml
type: custom:expander-card
gap: 0.6em
padding: 1em
clear: false
title: Expander
overlay-margin: 2em
child-padding: '' # default was 0.5em
button-background: transparent
cards:
  - type: entities
    entities:
      - entity: sun.sun
        name: This is an entity
```

![image](https://github.com/MelleD/lovelace-expander-card/assets/4663766/abde7557-144e-442e-b1f8-490702e37434)
